# .github/workflows/generate-stats.yml
name: Generate All Repo Stats

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the job automatically every Sunday at 05:00 UTC
  schedule:
    - cron: '0 5 * * 0'

jobs:
  run-ghrs-with-matrix:
    runs-on: ubuntu-latest
    strategy:
      # Do not cancel other jobs if one fails.
      fail-fast: false
      # IMPORTANT: Run jobs one by one to avoid commit conflicts on the data branch.
      max-parallel: 1
      matrix:
        # The list of repositories to generate reports for.
        repo:
          - 'AmosDinh/AmosDinh.github.io'
          - 'AmosDinh/bachelorthesis_security-research-graph-learning'
          - 'AmosDinh/BikePricePredict'
          - 'AmosDinh/Bot-or-User_Twitter-Classification'
          - 'AmosDinh/buildingGameBot'
          - 'AmosDinh/CNNBirdseye'
          - 'AmosDinh/colab_ssh'
          - 'AmosDinh/coursera-deep-learning-specialization'
          - 'AmosDinh/CryptoExchange_DataCollector_'
          - 'AmosDinh/decimal_binary_converter'
          - 'AmosDinh/diffusers'
          - 'AmosDinh/FileSaver.js'
          - 'AmosDinh/firecrawl'
          - 'AmosDinh/Fitbit_SleepData_Analysis'
          - 'AmosDinh/flvToMP4.py'
          - 'AmosDinh/Gallery_js'
          - 'AmosDinh/Generative_Clothes2Person'
          - 'AmosDinh/GNNpapersearch'
          - 'AmosDinh/GNNTwitteranalysis'
          - 'AmosDinh/GoogleAiStudio_SetSystemInstructionsAutomatically'
          - 'AmosDinh/googleSearcher'
          - 'AmosDinh/GraphStructureLearning'
          - 'AmosDinh/HDFS_python_demo'
          - 'AmosDinh/IceCreamEmpire_S4'
          - 'AmosDinh/jRDF2Vec'
          - 'AmosDinh/L1B3RT45'
          - 'AmosDinh/langchain'
          - 'AmosDinh/MachineLearningCourse'
          - 'AmosDinh/Mandelbrot'
          - 'AmosDinh/markdown2png'
          - 'AmosDinh/MultiLayerPerceptron'
          - 'AmosDinh/NeuroEvolution_NEAT'
          - 'AmosDinh/node_fontviewer'
          - 'AmosDinh/ov7670_VGA_color_SD_card_timelapse'
          - 'AmosDinh/pytorch_geometric'
          - 'AmosDinh/Reinforce_TrainReScheduling'
          - 'AmosDinh/Scrapegraph-ai'
          - 'AmosDinh/Skill_Job_GNN'
          - 'AmosDinh/snake'
          - 'AmosDinh/StableCascadeInference'
          - 'AmosDinh/StableDiffusion_Chairs'
          - 'AmosDinh/tictactoAlgo'
          - 'AmosDinh/WebProgramming-Project-Semester3'
          - 'AmosDinh/zed_settings'

    steps:
      - name: Generate repo traffic stats
        # Using the official v1.4.2 release and its correct parameters
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          # The repository to fetch stats for (from the matrix)
          repository: ${{ matrix.repo }}
          # The correct parameter name for the token is 'ghtoken'
          ghtoken: ${{ secrets.GH_PAT }}
