# .github/workflows/generate-stats.yml
name: Generate All Repo Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 0'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          # --- Your list of repositories ---
          - 'AmosDinh/AmosDinh.github.io'
          - 'AmosDinh/bachelorthesis_security-research-graph-learning'
          - 'AmosDinh/BikePricePredict'
          - 'AmosDinh/Bot-or-User_Twitter-Classification'
          - 'AmosDinh/buildingGameBot'
          - 'AmosDinh/CNNBirdseye'
          - 'AmosDinh/colab_ssh'
          - 'AmosDinh/coursera-deep-learning-specialization'
          - 'AmosDinh/CryptoExchange_DataCollector_'
          - 'AmosDinh/decimal_binary_converter'
          - 'AmosDinh/diffusers'
          - 'AmosDinh/FileSaver.js'
          - 'AmosDinh/firecrawl'
          - 'AmosDinh/Fitbit_SleepData_Analysis'
          - 'AmosDinh/flvToMP4.py'
          - 'AmosDinh/Gallery_js'
          - 'AmosDinh/Generative_Clothes2Person'
          - 'AmosDinh/GNNpapersearch'
          - 'AmosDinh/GNNTwitteranalysis'
          - 'AmosDinh/GoogleAiStudio_SetSystemInstructionsAutomatically'
          - 'AmosDinh/googleSearcher'
          - 'AmosDinh/GraphStructureLearning'
          - 'AmosDinh/HDFS_python_demo'
          - 'AmosDinh/IceCreamEmpire_S4'
          - 'AmosDinh/jRDF2Vec'
          - 'AmosDinh/L1B3RT45'
          - 'AmosDinh/langchain'
          - 'AmosDinh/MachineLearningCourse'
          - 'AmosDinh/Mandelbrot'
          - 'AmosDinh/markdown2png'
          - 'AmosDinh/MultiLayerPerceptron'
          - 'AmosDinh/NeuroEvolution_NEAT'
          - 'AmosDinh/node_fontviewer'
          - 'AmosDinh/ov7670_VGA_color_SD_card_timelapse'
          - 'AmosDinh/pytorch_geometric'
          - 'AmosDinh/Reinforce_TrainReScheduling'
          - 'AmosDinh/Scrapegraph-ai'
          - 'AmosDinh/Skill_Job_GNN'
          - 'AmosDinh/snake'
          - 'AmosDinh/StableCascadeInference'
          - 'AmosDinh/StableDiffusion_Chairs'
          - 'AmosDinh/tictactoAlgo'
          - 'AmosDinh/WebProgramming-Project-Semester3'
          - 'AmosDinh/zed_settings'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # --- THIS IS THE NEW STEP ---
      # It replaces the '/' in the repo name with '_' and saves it to an environment variable.
      - name: Create sanitized repo name for directory path
        run: echo "SANITIZED_REPO_NAME=$(echo ${{ matrix.repo }} | sed 's/\//_/g')" >> $GITHUB_ENV

      # This step now uses the environment variable created above.
      - name: Generate repo traffic stats
        uses: jgehrcke/github-repo-stats@v2
        with:
          github-token: ${{ secrets.GH_PAT }}
          repository: ${{ matrix.repo }}
          
          # --- THIS LINE IS CHANGED ---
          # Use the sanitized name from the environment variable.
          svg-export-path: './stats-output/${{ env.SANITIZED_REPO_NAME }}/'
          
          commit-message: 'docs: update repository traffic stats'
          commit-author-name: 'GitHub Actions'
          commit-author-email: 'actions@github.com'
